#!/usr/bin/env python3
# NGS asset converter: 8-bit indexed BMP -> RGBA8 PNG (palette idx 0 = transparent),
# NSP (4*int16 LE per rect) -> samples/ngs/assets/Atlases.hx literal table.
import os, struct, zlib

# .../lub/samples/ngs/scripts から各 dir を解決。ngs は lub の兄弟。
HERE = os.path.dirname(os.path.abspath(__file__))
LUB_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))   # .../lub
NGS_DIR = os.path.abspath(os.path.join(LUB_ROOT, "..", "ngs"))      # .../ngs
DATA_DIR = os.path.abspath(os.path.join(HERE, "..", "data"))
ASSETS_DIR = os.path.abspath(os.path.join(HERE, "..", "assets"))
ATLASES_HX = os.path.join(ASSETS_DIR, "Atlases.hx")

def read_indexed_bmp(path):
    with open(path, "rb") as f:
        b = f.read()
    if b[0:2] != b"BM":
        raise SystemExit(f"{path}: not a BMP")
    pixoff = struct.unpack_from("<I", b, 10)[0]
    hdr = struct.unpack_from("<I", b, 14)[0]
    w = struct.unpack_from("<i", b, 18)[0]
    h = struct.unpack_from("<i", b, 22)[0]
    bpp = struct.unpack_from("<H", b, 28)[0]
    if bpp != 8:
        raise SystemExit(f"{path}: expected 8bpp indexed, got {bpp}")
    pal_off = 14 + hdr
    ncol = struct.unpack_from("<I", b, 46)[0] or 256
    palette = []
    for i in range(ncol):
        bb, gg, rr, _ = b[pal_off + i*4 : pal_off + i*4 + 4]
        palette.append((rr, gg, bb))
    top_down = h < 0
    H = abs(h)
    row_size = (w + 3) & ~3   # rows padded to 4 bytes
    idx = [[0]*w for _ in range(H)]
    for ry in range(H):
        src_row = ry if top_down else (H - 1 - ry)
        base = pixoff + src_row * row_size
        for x in range(w):
            idx[ry][x] = b[base + x]
    return w, H, palette, idx

def write_png_rgba(path, w, h, rgba):  # rgba: bytes len w*h*4
    def chunk(tag, data):
        c = tag + data
        return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xffffffff)
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)  # 8-bit, color type 6 (RGBA)
    raw = bytearray()
    for y in range(h):
        raw.append(0)  # filter none
        raw.extend(rgba[(y*w)*4 : (y*w + w)*4])
    idat = zlib.compress(bytes(raw), 9)
    with open(path, "wb") as f:
        f.write(sig + chunk(b"IHDR", ihdr) + chunk(b"IDAT", idat) + chunk(b"IEND", b""))

def bmp_to_png(name):
    w, h, pal, idx = read_indexed_bmp(os.path.join(NGS_DIR, name + ".bmp"))
    out = bytearray(w*h*4)
    for y in range(h):
        for x in range(w):
            ci = idx[y][x]
            r, g, b = pal[ci]
            o = (y*w + x)*4
            if ci == 0:
                out[o:o+4] = bytes((0, 0, 0, 0))       # palette idx 0 -> transparent
            else:
                out[o:o+4] = bytes((r, g, b, 255))
    write_png_rgba(os.path.join(DATA_DIR, name + ".png"), w, h, bytes(out))
    print(f"  {name}.png  {w}x{h}")

def read_nsp(name):
    # NSP format: plain text, one rect per line, "x,y,w,h," (trailing comma)
    with open(os.path.join(NGS_DIR, name + ".nsp"), "r") as f:
        text = f.read()
    rects = []
    for line in text.splitlines():
        line = line.strip().rstrip(",")
        if not line:
            continue
        parts = [int(v) for v in line.split(",")]
        x, y, w, h = parts[0], parts[1], parts[2], parts[3]
        rects.append((x, y, w, h))
    return rects

def gen_atlases():
    sheets = [("cursor", read_nsp("cursor")),
              ("jiki",   read_nsp("jiki")),
              ("enemy",  read_nsp("enemy"))]
    lines = ["package assets;", "",
             "// GENERATED by samples/ngs/scripts/convert.py — do not edit by hand.",
             "// Source NSP rect order is preserved (gameplay code indexes by number).",
             "import render.Rect;", "", "class Atlases {"]
    for nm, rects in sheets:
        lines.append(f"  public static final {nm}: Array<Rect> = [")
        for (x, y, w, h) in rects:
            lines.append(f"    {{ x: {x}, y: {y}, w: {w}, h: {h} }},")
        lines.append("  ];")
    lines.append("}")
    with open(ATLASES_HX, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  Atlases.hx ({sum(len(r) for _, r in sheets)} rects)")

def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(ASSETS_DIR, exist_ok=True)
    print("BMP -> PNG:")
    for nm in ("cursor", "jiki", "enemy", "font"):
        bmp_to_png(nm)
    print("NSP -> Atlases.hx:")
    gen_atlases()

if __name__ == "__main__":
    main()
