package assets;

// GENERATED by samples/ngs/scripts/convert.py — do not edit by hand.
// Source NSP rect order is preserved (gameplay code indexes by number).
import render.Rect;

class Atlases {
	public static final cursor:Array<Rect> = [
		{
			x: 0,
			y: 0,
			w: 8,
			h: 8
		},
		{
			x: 8,
			y: 0,
			w: 8,
			h: 8
		},
		{
			x: 16,
			y: 0,
			w: 8,
			h: 8
		},
		{
			x: 24,
			y: 0,
			w: 8,
			h: 8
		},
	];
	public static final jiki:Array<Rect> = [
		{
			x: 0,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 16,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 32,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 48,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 64,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 0,
			y: 16,
			w: 16,
			h: 16
		},
		{
			x: 16,
			y: 16,
			w: 16,
			h: 16
		},
		{
			x: 32,
			y: 16,
			w: 16,
			h: 16
		},
		{
			x: 48,
			y: 16,
			w: 16,
			h: 16
		},
		{
			x: 64,
			y: 16,
			w: 16,
			h: 8
		},
		{
			x: 64,
			y: 24,
			w: 10,
			h: 5
		},
		{
			x: 64,
			y: 29,
			w: 6,
			h: 3
		},
		{
			x: 50,
			y: 18,
			w: 12,
			h: 14
		},
	];
	public static final enemy:Array<Rect> = [
		{
			x: 0,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 16,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 32,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 48,
			y: 0,
			w: 16,
			h: 16
		},
		{
			x: 0,
			y: 16,
			w: 16,
			h: 16
		},
		{
			x: 16,
			y: 16,
			w: 6,
			h: 7
		},
		{
			x: 22,
			y: 16,
			w: 6,
			h: 7
		},
		{
			x: 29,
			y: 16,
			w: 2,
			h: 16
		},
		{
			x: 30,
			y: 16,
			w: 2,
			h: 16
		},
		{
			x: 0,
			y: 32,
			w: 26,
			h: 32
		},
		{
			x: 27,
			y: 32,
			w: 26,
			h: 32
		},
		{
			x: 64,
			y: 0,
			w: 26,
			h: 32
		},
		{
			x: 64,
			y: 32,
			w: 26,
			h: 32
		},
		{
			x: 51,
			y: 21,
			w: 3,
			h: 3
		},
		{
			x: 51,
			y: 25,
			w: 3,
			h: 3
		},
		{
			x: 50,
			y: 16,
			w: 5,
			h: 4
		},
		{
			x: 55,
			y: 16,
			w: 1,
			h: 32
		},
		{
			x: 90,
			y: 0,
			w: 26,
			h: 32
		},
		{
			x: 32,
			y: 16,
			w: 6,
			h: 6
		},
		{
			x: 40,
			y: 16,
			w: 8,
			h: 8
		},
		{
			x: 32,
			y: 24,
			w: 8,
			h: 8
		},
		{
			x: 40,
			y: 24,
			w: 8,
			h: 8
		},
		{
			x: 90,
			y: 32,
			w: 26,
			h: 32
		},
	];
}
