#ifndef LUB_EMBEDDED_PRELUDE_H
#define LUB_EMBEDDED_PRELUDE_H

// Haxe -lua の出力に prepend する shim。
// (1) lub runtime は Lua 5.5 (utf8 built-in) だが、Haxe lua target が
//     require("lua-utf8") を出す前提なので alias を貼っておく。
// (2) Haxe extern (lub.Lub / lub.Gfx / lub.Phys2d / lub.Input / lub.Sys) は
//     class-qualified call (e.g. lub.Gfx.begin_pass) を emit するが、
//     lub C 側は global function (begin_pass) として expose しているので、
//     globals を namespace table に集約してギャップを埋める。
//     lub.Io は @:luaRequire("lub_io") 経由で別経路なので shim 不要。
// (3) Haxe lua target は Int の bitwise (^, &, |, <<, >>) を _hx_bit (= bit32)
//     経由で呼ぶ。Lua 5.5 は native bitwise operator を持つが bit32 module
//     を持たないため、Lua 5.5 native bitwise op で bit32 互換 table を
//     preload しておく。
// (4) Haxe Math.atan2 は math.atan2 を emit するが、Lua 5.3+ で削除された
//     (math.atan(y, x) に統合)。Lua 5.5 用に atan2 を補完する。
static const char HAXE_PRELUDE[] =
    "package.preload[\"lua-utf8\"] = function()\n"
    "  return {\n"
    "    len = string.len, char = string.char,\n"
    "    upper = string.upper, lower = string.lower,\n"
    "    find = string.find, sub = string.sub, byte = string.byte,\n"
    "  }\n"
    "end\n"
    "package.preload[\"bit32\"] = function()\n"
    "  local M = {}\n"
    "  local MASK = 0xFFFFFFFF\n"
    "  function M.band(a, b, ...) local r = a & b; for i=1,select('#',...) do "
    "r = r & (select(i,...)) end; return r & MASK end\n"
    "  function M.bor(a, b, ...)  local r = a | b; for i=1,select('#',...) do "
    "r = r | (select(i,...)) end; return r & MASK end\n"
    "  function M.bxor(a, b, ...) local r = a ~ b; for i=1,select('#',...) do "
    "r = r ~ (select(i,...)) end; return r & MASK end\n"
    "  function M.bnot(a) return (~a) & MASK end\n"
    "  function M.lshift(a, n) return (a << n) & MASK end\n"
    "  function M.rshift(a, n) return (a & MASK) >> n end\n"
    "  function M.arshift(a, n) local s = a & MASK; if s >= 0x80000000 then s "
    "= s - 0x100000000 end; return (s >> n) & MASK end\n"
    "  return M\n"
    "end\n"
    "if math.atan2 == nil then math.atan2 = function(y, x) return math.atan(y, "
    "x) end end\n"
    "lub = lub or {}\n"
    "lub.Lub = { config = config, quit = quit }\n"
    "lub.Gfx = {\n"
    "  begin_pass = begin_pass, end_pass = end_pass,\n"
    "  use_shader = use_shader, use_shader_compute = use_shader_compute,\n"
    "  use_buffer = use_buffer, use_texture = use_texture,\n"
    "  draw = draw, dispatch = dispatch, readback = readback,\n"
    "  main_tex = main_tex, size = gfx_size,\n"
    "  VERTEX = VERTEX, INDEX = INDEX, UNIFORM = UNIFORM, STORAGE = STORAGE,\n"
    "  RGBA8 = RGBA8, R8 = R8, RG8 = RG8,\n"
    "  R16F = R16F, RG16F = RG16F, R32F = R32F,\n"
    "  RGBA16F = RGBA16F, RGBA32F = RGBA32F,\n"
    "  DEPTH16 = DEPTH16, DEPTH24_STENCIL8 = DEPTH24_STENCIL8, DEPTH32F = "
    "DEPTH32F,\n"
    "  CLEAR = CLEAR, LOAD = LOAD, DONTCARE = DONTCARE, STORE = STORE,\n"
    "  NONE = NONE, ALPHA = ALPHA, ADDITIVE = ADDITIVE, MULTIPLY = MULTIPLY,\n"
    "  BACK = BACK, FRONT = FRONT,\n"
    "  TRIANGLES = TRIANGLES, TRIANGLE_STRIP = TRIANGLE_STRIP,\n"
    "  LINES = LINES, LINE_STRIP = LINE_STRIP, POINTS = POINTS,\n"
    "  LINEAR = LINEAR, NEAREST = NEAREST, REPEAT = REPEAT, CLAMP = CLAMP,\n"
    "}\n"
    "do local P={}\n"
    "for _,n in "
    "ipairs({'world','begin','world_info','body','box','circle','capsule',"
    "'segment','polygon','chain','chain_segments',"
    "'joint','joint_info','joint_force','joint_torque','joint_angle',"
    "'joint_translation','joint_speed','joint_length','joint_motor_force',"
    "'joint_motor_torque','joint_set_motor','joint_set_limit',"
    "'joint_set_spring','joint_set_target','step','pose','velocity','mass',"
    "'center','world_point','local_point','velocity_at','body_shapes',"
    "'body_joints','body_contacts','shape_test_point','shape_raycast',"
    "'shape_closest_point','shape_aabb','shape_info','shape_set_material',"
    "'shape_set_filter','shape_set_events','contacts','body_events','sensors',"
    "'raycast','overlap_aabb','shape_cast','cast_mover','collide_mover',"
    "'explode','debug','profile','counters','add_force','add_force_center',"
    "'add_impulse','add_impulse_center','add_torque','add_angular_impulse',"
    "'set_velocity','teleport','set_target','set_mass_data'}) do "
    "P['phys2d_'..n]=_G['phys2d_'..n] "
    "end\n"
    "P.STATIC=STATIC;P.KINEMATIC=KINEMATIC;P.DYNAMIC=DYNAMIC;lub.Phys2d=P end\n"
    "do local P={}\n"
    "for _,n in ipairs({'world','begin','world_info','body','sphere','box',"
    "'capsule','cylinder','cone','hull','mesh','height_field','compound',"
    "'joint','joint_info','joint_force','joint_torque','joint_angle',"
    "'joint_translation','joint_speed','joint_length','joint_motor_force',"
    "'joint_motor_torque','joint_set_motor','joint_set_limit',"
    "'joint_set_spring','joint_set_target','step','pose','velocity','mass',"
    "'center','world_point','local_point','velocity_at','body_shapes',"
    "'body_joints','body_contacts','shape_raycast','shape_closest_point',"
    "'shape_aabb','shape_info','shape_set_material','shape_set_filter',"
    "'shape_set_events','contacts','body_events','sensors','joint_events',"
    "'raycast','overlap_aabb','overlap_shape','shape_cast','cast_mover',"
    "'collide_mover','profile','counters','add_force','add_force_center',"
    "'add_impulse','add_impulse_center','add_torque','add_angular_impulse',"
    "'set_velocity','teleport','set_target'}) do "
    "P['phys3d_'..n]=_G['phys3d_'..n] "
    "end\n"
    "P.STATIC=STATIC;P.KINEMATIC=KINEMATIC;P.DYNAMIC=DYNAMIC;lub.Phys3d=P end\n"
    "lub.Input = { key_down = key_down, key_pressed = key_pressed,\n"
    "  key_released = key_released, mouse_delta = mouse_delta,\n"
    "  mouse_down = mouse_down, mouse_pressed = mouse_pressed,\n"
    "  mouse_released = mouse_released, mouse_pos = mouse_pos }\n"
    "lub.Profiler = { enabled = profile_enabled,\n"
    "  begin_scope = profile_begin, end_scope = profile_end,\n"
    "  reset = profile_reset, report = profile_report }\n"
    "lub.Mesh = { surface_nets = surface_nets }\n"
    "lub.Sys = { file_mtime = file_mtime, request_file = request_file,\n"
    "  is_web = is_web,\n"
    "  fnv1a64 = fnv1a64,\n"
    "  actual_fps = actual_fps }\n";

#endif
