#ifndef LUB_EMBEDDED_SERVE_PAGE_H
#define LUB_EMBEDDED_SERVE_PAGE_H

// Self-contained HTML page for lub --serve.
// Includes: WebGPU init, Slang WASM bridge, EventSource (SSE) client,
// lub.js loader with MEMFS overlay.
// Template variable: {{ENTRY}} is replaced at runtime with the game entry name.

static const char SERVE_PAGE_HTML[] =
    "<!DOCTYPE html>\n"
    "<html><head><meta charset=\"UTF-8\">\n"
    "<style>\n"
    "html,body{margin:0;height:100%;background:#000;overflow:hidden;"
    "display:flex;align-items:center;justify-content:center}\n"
    "canvas{display:block;max-width:100%;max-height:100%}\n"
    "#status{position:fixed;top:10px;left:10px;color:#0f0;font:14px monospace;"
    "z-index:10;pointer-events:none}\n"
    "</style></head><body>\n"
    "<div id=\"status\">connecting...</div>\n"
    "<canvas id=\"canvas\" width=\"1280\" height=\"720\" "
    "tabindex=\"0\"></canvas>\n"
    // Host bridge (window.lubHost) from the game dir; the server answers an
    // empty script when the game has none. Loaded synchronously before the
    // main script so lubHost exists before any Lua runs.
    "<script src=\"/host.js\"></script>\n"
    "<script>\n"
    "'use strict';\n"
    "const ENTRY='{{ENTRY}}';\n"
    "const canvas=document.getElementById('canvas');\n"
    "const statusEl=document.getElementById('status');\n"
    "let pendingFiles=null,wasmStarted=false;\n"
    "\n"
    "function writeFileEnsureDir(FS,path,content){\n"
    "  const parts=path.split('/');\n"
    "  let cur='';\n"
    "  for(let i=0;i<parts.length-1;i++){\n"
    "    cur=cur?cur+'/'+parts[i]:parts[i];\n"
    "    try{FS.mkdir(cur);}catch{}\n"
    "  }\n"
    "  try{FS.unlink(path);}catch{}\n"
    "  FS.writeFile(path,content);\n"
    "}\n"
    "\n"
    "function overlayFiles(FS,files){\n"
    "  for(const[p,c]of Object.entries(files)){\n"
    "    const full='samples/'+ENTRY+'/'+p;\n"
    "    writeFileEnsureDir(FS,full,c);\n"
    "  }\n"
    "}\n"
    "\n"
    "// --- WebGPU init ---\n"
    "async function initWebGPU(){\n"
    "  if(!('gpu' in navigator))throw new Error('WebGPU not available');\n"
    "  const adapter=await navigator.gpu.requestAdapter();\n"
    "  if(!adapter)throw new Error('No WebGPU adapter');\n"
    "  const wanted=[];\n"
    "  for(const f of['depth32float-stencil8','float32-filterable']){\n"
    "    if(adapter.features?.has?.(f))wanted.push(f);\n"
    "  }\n"
    "  return await adapter.requestDevice({requiredFeatures:wanted});\n"
    "}\n"
    "\n"
    "// --- Slang WASM bridge ---\n"
    "let slangReady=false;\n"
    "async function initSlang(){\n"
    "  try{\n"
    "    const importer=new Function('u','return import(u)');\n"
    "    const mod=await importer('/slang/slang-wasm.js');\n"
    "    const factory=mod.default;\n"
    "    if(typeof factory!=='function')throw new Error('no factory');\n"
    "    const main=await factory({\n"
    "      locateFile:p=>p.endsWith('.wasm')?'/slang/'+p:p\n"
    "    });\n"
    "    const gs=main.createGlobalSession();\n"
    "    if(!gs)throw new Error('createGlobalSession failed');\n"
    "    const targets=main.getCompileTargets();\n"
    "    let wgslTarget=-1;\n"
    "    for(const t of "
    "targets){if(t.name==='WGSL'){wgslTarget=t.value;break;}}\n"
    "    if(wgslTarget<0)throw new Error('no WGSL target');\n"
    "    let sharedSession=null,moduleSeq=0;\n"
    "\n"
    "    function remapWgslGroups(src){\n"
    "      const "
    "re=/"
    "@binding\\((\\d+)\\)\\s+@group\\((\\d+)\\)\\s+var(<[^>]*>)?(\\s+[A-Za-z_]"
    "\\w*\\s*:\\s*[A-Za-z_]\\w*)/g;\n"
    "      let count=0;\n"
    "      const wgsl=src.replace(re,(full,_b,_g,varTpl,tail)=>{\n"
    "        count++;\n"
    "        const tpl=(varTpl||'').toLowerCase();\n"
    "        const tail_l=(tail||'').toLowerCase();\n"
    "        const colon=tail_l.lastIndexOf(':');\n"
    "        const typeId=colon>=0?tail_l.slice(colon+1).trim():'';\n"
    "        let ng=_g;\n"
    "        if(tpl.startsWith('<uniform'))ng='0';\n"
    "        else if(tpl.startsWith('<storage'))ng='1';\n"
    "        else "
    "if(typeId.startsWith('texture_')||typeId==='sampler'||typeId==='sampler_"
    "comparison')ng='1';\n"
    "        return full.replace(/@group\\(\\d+\\)/,'@group('+ng+')');\n"
    "      });\n"
    "      return{wgsl,remapped:count};\n"
    "    }\n"
    "\n"
    "    window.slangCompile=async(src,entry,stage)=>{\n"
    "      const STAGES=[1,5,6];\n"
    "      let "
    "userModule=null,ep=null,composite=null,linked=null,layout=null;\n"
    "      try{\n"
    "        if(!sharedSession){\n"
    "          sharedSession=gs.createSession(wgslTarget);\n"
    "          if(!sharedSession)return{error:'createSession failed'};\n"
    "        }\n"
    "        const modName='user_'+(moduleSeq++);\n"
    "        "
    "userModule=sharedSession.loadModuleFromSource(src,modName,modName+'.slang'"
    ");\n"
    "        if(!userModule){const "
    "e=main.getLastError?.();return{error:'loadModule: '+(e?.message||'?')};}\n"
    "        ep=userModule.findAndCheckEntryPoint(entry,STAGES[stage]);\n"
    "        if(!ep){const e=main.getLastError?.();return{error:'entryPoint: "
    "'+(e?.message||'?')};}\n"
    "        "
    "composite=sharedSession.createCompositeComponentType([userModule,ep]);\n"
    "        if(!composite){const "
    "e=main.getLastError?.();return{error:'composite: '+(e?.message||'?')};}\n"
    "        linked=composite.link();\n"
    "        if(!linked){const e=main.getLastError?.();return{error:'link: "
    "'+(e?.message||'?')};}\n"
    "        const rawWgsl=linked.getEntryPointCode(0,0);\n"
    "        if(!rawWgsl||rawWgsl==='Error'||!rawWgsl.length){\n"
    "          const e=main.getLastError?.();return{error:'getEntryPointCode: "
    "'+(e?.message||'?')};\n"
    "        }\n"
    "        const{wgsl:groupWgsl}=remapWgslGroups(rawWgsl);\n"
    "        const wgsl=groupWgsl.replace(\n"
    "          /texture_storage_(\\w+)<([^,]+),\\s*read_write>/g,\n"
    "          'texture_storage_$1<$2, write>');\n"
    "        let reflectObj={};\n"
    "        "
    "try{layout=linked.getLayout(0);if(layout)reflectObj=layout.toJsonObject()?"
    "?{};}catch{}\n"
    "        return{wgsl,reflectJson:JSON.stringify(reflectObj)};\n"
    "      }catch(e){return{error:'slangCompile threw: '+(e?.message??e)};}\n"
    "      finally{\n"
    "        try{layout?.delete?.();}catch{}\n"
    "        try{linked?.delete?.();}catch{}\n"
    "        try{composite?.delete?.();}catch{}\n"
    "        try{ep?.delete?.();}catch{}\n"
    "        try{userModule?.delete?.();}catch{}\n"
    "      }\n"
    "    };\n"
    "    slangReady=true;\n"
    "    console.log('[serve] slang-wasm ready');\n"
    "  }catch(e){\n"
    "    console.error('[serve] slang-wasm init failed:',e);\n"
    "  }\n"
    "}\n"
    "\n"
    "// --- WASM startup ---\n"
    "async function startWasm(){\n"
    "  if(wasmStarted)return;\n"
    "  wasmStarted=true;\n"
    "  statusEl.textContent='initializing WebGPU...';\n"
    "  let device;\n"
    "  try{device=await initWebGPU();}catch(e){\n"
    "    statusEl.textContent='WebGPU init failed: '+e.message;return;\n"
    "  }\n"
    "  const seenErrors=new Set();\n"
    "  device.addEventListener('uncapturederror',e=>{\n"
    "    const msg=String(e.error?.message??e.error);\n"
    "    if(seenErrors.has(msg))return;seenErrors.add(msg);\n"
    "    console.error('[webgpu]',msg);\n"
    "  });\n"
    "  statusEl.textContent='initializing Slang...';\n"
    "  await initSlang();\n"
    "  statusEl.textContent='loading WASM...';\n"
    "  const moduleConfig={\n"
    "    canvas,\n"
    "    preinitializedWebGPUDevice:device,\n"
    "    print:t=>console.log(t),\n"
    "    printErr:t=>console.error(t),\n"
    "    locateFile:p=>'/wasm/'+p,\n"
    "    preRun:[],\n"
    "    arguments:[ENTRY]\n"
    "  };\n"
    "  const DEP='serve_overlay';\n"
    "  moduleConfig.preRun.push(function(){\n"
    "    const M=moduleConfig;\n"
    "    M.addRunDependency(DEP);\n"
    "    const origRemove=M.removeRunDependency;\n"
    "    M.removeRunDependency=function(id){\n"
    "      origRemove.call(M,id);\n"
    "      if(id==='datafile_lub.data'){\n"
    "        try{\n"
    "          const FS=M.FS??window.FS;\n"
    "          if(pendingFiles)overlayFiles(FS,pendingFiles);\n"
    "          console.log('[serve] game files overlayed');\n"
    "          statusEl.style.display='none';\n"
    "        }catch(e){console.error('[serve] overlay error:',e);}\n"
    "        "
    "finally{origRemove.call(M,DEP);M.removeRunDependency=origRemove;}\n"
    "      }\n"
    "    };\n"
    "  });\n"
    "  window.Module=moduleConfig;\n"
    "  const s=document.createElement('script');\n"
    "  s.src='/wasm/lub.js';\n"
    "  document.body.appendChild(s);\n"
    "}\n"
    "\n"
    "// --- SSE connection ---\n"
    "const es=new EventSource('/events');\n"
    "es.addEventListener('files',e=>{\n"
    "  const msg=JSON.parse(e.data);\n"
    "  if(!wasmStarted){\n"
    "    pendingFiles=msg.files;\n"
    "    statusEl.textContent='files received, starting...';\n"
    "    startWasm();\n"
    "  }else{\n"
    "    const FS=window.FS;\n"
    "    if(FS)overlayFiles(FS,msg.files);\n"
    "  }\n"
    "});\n"
    "es.onerror=()=>{statusEl.textContent='SSE "
    "disconnected';statusEl.style.display='block';};\n"
    "es.onopen=()=>{if(wasmStarted)statusEl.style.display='none';};\n"
    "</script></body></html>\n";

#endif
