#pragma once

typedef enum {
    SGL_BUFFER_VERTEX = 1,
    SGL_BUFFER_INDEX,
    SGL_BUFFER_UNIFORM,
    SGL_BUFFER_STORAGE,
} SglBufferType;

typedef enum {
    SGL_PF_RGBA8 = 1,
    SGL_PF_R8,
    SGL_PF_RG8,
    SGL_PF_RGBA16F,
    SGL_PF_RGBA32F,
    SGL_PF_DEPTH16,
    SGL_PF_DEPTH24_STENCIL8,
    SGL_PF_DEPTH32F,
    SGL_PF_BGRA8,
} SglPixelFormat;

typedef enum { SGL_LOAD_CLEAR = 1, SGL_LOAD_LOAD, SGL_LOAD_DONTCARE } SglLoadAction;
typedef enum { SGL_STORE_STORE = 1, SGL_STORE_DONTCARE } SglStoreAction;
typedef enum { SGL_BLEND_NONE = 1, SGL_BLEND_ALPHA, SGL_BLEND_ADDITIVE, SGL_BLEND_MULTIPLY } SglBlend;
typedef enum { SGL_CULL_NONE = 1, SGL_CULL_BACK, SGL_CULL_FRONT } SglCull;
typedef enum {
    SGL_PRIM_TRIANGLES = 1, SGL_PRIM_TRIANGLE_STRIP,
    SGL_PRIM_LINES, SGL_PRIM_LINE_STRIP, SGL_PRIM_POINTS,
} SglPrimitive;
typedef enum { SGL_FILTER_LINEAR = 1, SGL_FILTER_NEAREST } SglFilter;
typedef enum { SGL_WRAP_REPEAT  = 1, SGL_WRAP_CLAMP    } SglWrap;
